openapi: 3.0.4
info:
  title: Grupo 13 - Tech Challenger 1° Fase
  description: |-
    Sistema robusto que permita a todos os restaurantes gerenciar eficientemente suas operações, enquanto os clientes poderão consultar informações, deixar avaliações e fazer pedidos online.
    Devido à limitação de recursos financeiros, foi acordado que a entrega do sistema será realizada em fases, garantindo que cada etapa seja desenvolvida de forma cuidadosa e eficaz.
  version: 1.0.0


servers:
  - url: http://localhost:8080

paths:
  /user/login:
    post:
      tags:
        - User
      summary: Log user into the system
      description: Authenticates a user and returns a session token.
      operationId: loginUserSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: 'root'
                password:
                  type: string
                  example: 'root'
      responses:
        '200':
          description: Successful login
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"
        

  /user:
    post:
      tags:
        - User
      summary: Create user
      description: This can only be done by the logged-in user.
      operationId: createUser
      requestBody:
        description: Created user object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: admin
                password:
                  type: string
                  example: 12345
                firstName:
                  type: string
                  example: João
                lastName:
                  type: string
                  example: Marcos
                phone:
                  type: string
                  example: '9999999999'
                email:
                  type: string
                  example: 'teste@gmail.com'
                role:
                  type: string
                  example: 'client'
                countryCode:
                  type: string
                  example: '+55'
                postalCode:
                  type: string
                  example: '12345678932'
                state:
                  type: string
                  example: 'São Paulo'
                city:
                  type: string
                  example: 'Bauru'
                street:
                  type: string
                  example: 'Rua exemplo'
                number:
                  type: string
                  example: '321'
                complement:
                  type: string
                  example: 'AP 123'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  login:
                    type: string
                    example: admin
                  firstName:
                    type: string
                    example: João
                  lastName:
                    type: string
                    example: Marcos
                  phone:
                    type: string
                    example: '9999999999'
                  email:
                    type: string
                    example: 'teste@gmail.com'
                  role:
                    type: string
                    example: 'client'
                  countryCode:
                    type: string
                    example: '+55'
                  postalCode:
                    type: string
                    example: '12345678932'
                  state:
                    type: string
                    example: 'São Paulo'
                  city:
                    type: string
                    example: 'Bauru'
                  street:
                    type: string
                    example: 'Rua exemplo'
                  number:
                    type: string
                    example: '321'
                  complement:
                    type: string
                    example: 'AP 123'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"

    get:
      tags:
        - User
      summary: Get all users
      description: Returns a list of all users.
      operationId: getAllUsers
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"
  /user/findByName/{name}:
    get:
      tags:
        - User
      summary: Get user by ID
      description: Returns a single user.
      operationId: getUserByName
      parameters:
        - name: name
          in: path
          description: Name of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"
  /user/{id}:
    get:
      tags:
        - User
      summary: Get user by ID
      description: Returns a single user.
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"

    delete:
      tags:
        - User
      summary: Delete user by ID
      description: This can only be done by the logged-in user.
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: The user ID that needs to be deleted
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"

    put:
      tags:
        - User
      summary: Update user by ID
      description: Updates an existing user with the given ID.
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: ID of the user to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"
                

  /user/new-password:
    put:
      tags:
        - User
      summary: Change user password
      description: Update the password of the logged user.
      operationId: changeUserPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: 'newpassword123'
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unautorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidToken"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        login:
          type: string
          example: admin
        firstName:
          type: string
          example: João
        lastName:
          type: string
          example: Marcos
        phone:
          type: string
          example: '9999999999'
        email:
          type: string
          example: 'teste@gmail.com'
        role:
          type: string
          example: 'client'
        countryCode:
          type: string
          example: '+55'
        postalCode:
          type: string
          example: '12345678932'
        state:
          type: string
          example: 'São Paulo'
        city:
          type: string
          example: 'Bauru'
        street:
          type: string
          example: 'Rua exemplo'
        number:
          type: string
          example: '321'
        complement:
          type: string
          example: 'AP 123'
          

    NotFound:
      type: object
      properties:
        type:
          type: string
          example: about:blank
        title:
          type: string
          example: Resource not found
        status:
          type: string
          example: 404
        detail:
          type: string
          example: Resource not found
        instance:
          type: string
          example: /api/v1/users
        timestamp:
          type: string
          example: '2025-09-15 11:30:45'
          
          
    BadRequest:
      type: object
      properties:
        type:
          type: string
          example: about:blank
        title:
          type: string
          example: Multiple errors
        status:
          type: string
          example: 400
        detail:
          type: string
          example: ['Email is required.']
        instance:
          type: string
          example: /api/v1/users
        timestamp:
          type: string
          example: '2025-09-15 11:30:45'


    InvalidToken:
      type: object
      properties:
        type:
          type: string
          example: about:blank
        title:
          type: string
          example: Operation not allowed
        status:
          type: string
          example: 401
        detail:
          type: string
          example: Operation not allowed
        instance:
          type: string
          example: /api/v1/users
        timestamp:
          type: string
          example: '2025-09-15 11:30:45'


  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
